### ISSUE TITLE
BUG: Edge properties not accessible in `View`

### ISSUE THREAD

**Issue by ntolley** [jaxleyverse/jaxley#533]
Found while working on #523, it seems like the `edges` dataframe is not updated when accessing it through a view, for example
```py
net.cell(0).edges
```
Is just an empty dataframe, while `net.cell(0).nodes` is filled out correctly.

I'm taking a look at `_set_inds_in_view()` to try and narrow down the issue.

**Comment by michaeldeistler** [comment]
Hi Nick! This is expected behavior. When you do, e.g., `net.cell([0, 1]).edges`, it only shown synapses which are pre- **and** post-synaptically within this subnetwork:
![synapse_indexing_explanation](https://github.com/user-attachments/assets/9e3e41c7-c5f4-4186-a727-7f17f9648c0b)

If you need more flexible synapse indexing, you have to `query` the exact behaviour you want. E.g., to get all synapses that are post-synaptically connected to neuron `0`, do:
![synapse_indexing_explanation_complex](https://github.com/user-attachments/assets/08ffe590-2989-4408-9a3d-17c2317dba3c)

If you want all synapses where are connect pre- **or** post-synaptically, you would do:
```python
net.copy_node_property_to_edges("global_cell_index")
df = net.edges.query("post_global_cell_index in [0] or pre_global_cell_index in [0]")
net.selelct(edges=df.index, nodes=[0]).edges
```

I think that [this tutorial](https://jaxley.readthedocs.io/en/latest/tutorials/09_advanced_indexing.html) could also be helpful.

Let me know if anything is unclear!
Michael

**Comment by ntolley** [comment]
Ah this makes a ton of sense now, was a bit hasty with the issue reporting :wink: 

In this case I think the synapse recording PR should work just fine, thanks a bunch for explaining this!
